### PR TITLE
User authentication in dbConnect via ...  in scr_SparkSQL and scr_Hive

### PR DESCRIPTION
**Pull request by MarcinKosinski**
What if connection to HiveServer2 requires passing dbname or user or password parameters (?dbConnect)?
I also see lack of similar functionality in src_Hive(). Can authentication can be done in a different way?

### CODE REVIEW

**Comment by piccolbo** [comment]
Please bump to 0.5.0 (see semver.org). Everything else looking good.

**Comment by MarcinKosinski** [comment]
I've bumped version to `0.5.0`. Thanks for comments

**Comment by piccolbo** [comment]
Did you run R CMD check?

**Comment by MarcinKosinski** [comment]
Talking about  CRAN CHECK: it does not even work for me on `master` branch (mentioned this here https://github.com/piccolbo/dplyr.spark.hive/issues/16). I am not even aware if this package passed check for you, since you do not have any support of any continous-integration-tool. I've tried to synchronize `travis-ci` with my fork (here are results of last 11 builds of CRAN CHECK https://travis-ci.org/MarcinKosinski/dplyr.spark.hive/builds/) but I am having problems with specifying proper `.travis.yaml` file http://stackoverflow.com/questions/34642012/cant-install-dependencies-error-while-building-an-r-package-with-travis-ci . Moreover I see that you don't use roxygen2 package (https://github.com/yihui/roxygen2) to help yourself creating documentation and you are building documentation by yourself - this way may be hard to avoid warnings in CRAN CHECK.

**Comment by piccolbo** [comment]
Travis integration is not part of this pull and failed in the past. Please remove.

**Comment by piccolbo** [comment]
I run R CMD check all the time. I don't know what CRAN CHECK is. You can trust me or not. Travis is not God and I got tired of troubleshooting it and the checks are run post commit, which is the wrong time. But if you make it work and submit in a separate pull, I am  open to it.

**Comment by MarcinKosinski** [comment]
[CRAN CHECK is a more rigorus R CMD check](http://stackoverflow.com/a/10017736/3857701) . I'll undo last 11travis
commits. I can not always perform a proper R CMD check, since I have not
HADOOP_JAR file on every my machine.

2016-01-07 17:43 GMT+01:00 Antonio Piccolboni notifications@github.com:

**Comment by MarcinKosinski** [comment]
Removed travis commits.

**Comment by piccolbo** [comment]
After merging this and from master tests pass (little problem with parsing NAs ignored) -- c5e27cea42d277e1aaf03f5fac061d8c37b003e9
There aren't any tests against this new feature -- we don't have the capability to create users etc etc

**Comment by piccolbo** [comment]
And thanks for your contribution,

**Comment by MarcinKosinski** [comment]
Thanks for executing tests.

Marcin Kosinski

Dnia 12.01.2016 o godz. 01:23 Antonio Piccolboni notifications@github.com napisał(a):

**Pull request merged**
